# Generated by Django 4.1 on 2022-08-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_newsevents_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час публікації'),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Час зміни'),
        ),
    ]
